# Generated by Django 5.2.7 on 2025-10-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_event_participation'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='status',
            field=models.CharField(choices=[('REGISTERED', 'Inscrit'), ('CONFIRMED', 'Confirmé'), ('CANCELLED', 'Annulé')], default='REGISTERED', max_length=15),
        ),
    ]
