# Generated by Django 4.2 on 2025-10-23 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Utilisateur connecté (optionnel)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(blank=True, help_text='Adresse email (pour avis anonymes)', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='username',
            field=models.CharField(blank=True, help_text="Nom d'utilisateur (pour avis anonymes)", max_length=150, null=True),
        ),
    ]
