# Generated by Django 5.2.7 on 2025-10-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_feedback_rating_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(upload_to='events/', blank=True, null=True),
        ),
    ]


