# Generated by Django 5.2.7 on 2025-10-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, null=True, help_text='Nombre maximum de participants (laisser vide pour illimité)'),
        ),
    ]


