# Generated by Django 4.2 on 2025-10-29 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_feedback_user_alter_feedback_email_and_more'),
        ('myapp', '0007_event_max_participants'),
    ]

    operations = [
    ]
