# Generated by Django 4.2 on 2025-10-29 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_merge_20251030_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='myapp.event')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event Feedback',
                'verbose_name_plural': 'Event Feedbacks',
                'db_table': 'event_feedbacks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, help_text="Nom d'utilisateur (pour avis anonymes)", max_length=150, null=True)),
                ('email', models.EmailField(blank=True, help_text='Adresse email (pour avis anonymes)', max_length=254, null=True)),
                ('message', models.TextField(help_text='Message de feedback')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=True, help_text='Feedback approuvé')),
                ('user', models.ForeignKey(blank=True, help_text='Utilisateur connecté (optionnel)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platform_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Platform Feedback',
                'verbose_name_plural': 'Platform Feedbacks',
                'db_table': 'platform_feedbacks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
