# Generated by Django 4.2 on 2025-10-30 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_eventfeedback_platformfeedback_delete_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=255, verbose_name='Sujet')),
                ('type_reclamation', models.CharField(choices=[('COURS', 'Cours'), ('QUIZ', 'Quiz'), ('ENSEIGNANT', 'Enseignant'), ('BUG_TECHNIQUE', 'Bug Technique')], max_length=20, verbose_name='Type de réclamation')),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('RESOLUE', 'Résolue'), ('REJETEE', 'Rejetée')], default='EN_ATTENTE', max_length=15, verbose_name='Statut')),
                ('reponse_admin', models.TextField(blank=True, null=True, verbose_name="Réponse de l'administration")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('date_resolution', models.DateTimeField(blank=True, null=True, verbose_name='Date de résolution')),
                ('priorite', models.CharField(choices=[('BASSE', 'Basse'), ('MOYENNE', 'Moyenne'), ('HAUTE', 'Haute')], default='MOYENNE', max_length=10, verbose_name='Priorité')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to=settings.AUTH_USER_MODEL)),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations_traitees', to=settings.AUTH_USER_MODEL, verbose_name='Traité par')),
            ],
            options={
                'verbose_name': 'Réclamation',
                'verbose_name_plural': 'Réclamations',
                'db_table': 'reclamations',
                'ordering': ['-created_at'],
            },
        ),
    ]
